### ISSUE TITLE
`daqconf` was added into CMakeLists.txt

### ISSUE THREAD

**Issue by dingp** [DUNE-DAQ/listrev#38]
The nightly release failed to build since `daqconf` was added as a new dependency in `CMakeLists.txt`, but the Spack's package.py was yet to be updated.

However, the build still fails after adding it to package.py. I took a deeper look at the issue, and realized that `daqconf` does not provide any cmake targets, nor `listrev` uses any of it. 

~~It looks the `find_package(daqconf)` line was totally unnecessary. @plasorak Can we remove it?~~

Edit: I found it is used in `daq_codegen` call's `DEP_PKGS`. I'll see what I can do to fix the issue. Currently spack throws out cmake errors like the following:

```
CMake Error at /cvmfs/dunedaq-development.opensciencegrid.org/nightly/N22-09-16/spack-0.18.1-gcc-12.1.0/spack-0.18.1/opt/spack/gcc-12.1.0/daqconf-N22-09-16-4vsigntioc6ofmmyrh3dnwmn652e6sfi/lib64/daqconf/cmake/daqconfConfig.cmake:12 (message):
  File or directory
  /cvmfs/dunedaq-development.opensciencegrid.org/nightly/N22-09-16/spack-0.18.1-gcc-12.1.0/spack-0.18.1/opt/spack/gcc-12.1.0/daqconf-N22-09-16-4vsigntioc6ofmmyrh3dnwmn652e6sfi/lib64/daqconf/cmake/daqconfTargets.cmake
  referenced by variable targets_file does not exist !
Call Stack (most recent call first):
  /cvmfs/dunedaq-development.opensciencegrid.org/nightly/N22-09-16/spack-0.18.1-gcc-12.1.0/spack-0.18.1/opt/spack/gcc-12.1.0/daqconf-N22-09-16-4vsigntioc6ofmmyrh3dnwmn652e6sfi/lib64/daqconf/cmake/daqconfConfig.cmake:41 (set_and_check)
  CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!

```

**Comment by dingp** [comment]
This is fixed by https://github.com/DUNE-DAQ/daqconf/pull/194

**Comment by plasorak** [comment]
Huh, ok, yes, `listrev`'s configuration generation now relies on `daqconf`'s. Not sure if we could just get rid of it, maybe since this is only python this dependency could be removed?
